// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ReusableDelegationSetSpec defines the desired state of ReusableDelegationSet.
type ReusableDelegationSetSpec struct {

	// A unique string that identifies the request, and that allows you to retry
	// failed CreateReusableDelegationSet requests without the risk of executing
	// the operation twice. You must use a unique CallerReference string every time
	// you submit a CreateReusableDelegationSet request. CallerReference can be
	// any unique string, for example a date/time stamp.
	// +kubebuilder:validation:Required
	CallerReference *string `json:"callerReference"`
	// If you want to mark the delegation set for an existing hosted zone as reusable,
	// the ID for that hosted zone.
	HostedZoneID *string `json:"hostedZoneID,omitempty"`
}

// ReusableDelegationSetStatus defines the observed state of ReusableDelegationSet
type ReusableDelegationSetStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The ID that Amazon Route 53 assigns to a reusable delegation set.
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty"`
	// A complex type that contains a list of the authoritative name servers for
	// a hosted zone or for a reusable delegation set.
	// +kubebuilder:validation:Optional
	NameServers []*string `json:"nameServers,omitempty"`
}

// ReusableDelegationSet is the Schema for the ReusableDelegationSets API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type ReusableDelegationSet struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ReusableDelegationSetSpec   `json:"spec,omitempty"`
	Status            ReusableDelegationSetStatus `json:"status,omitempty"`
}

// ReusableDelegationSetList contains a list of ReusableDelegationSet
// +kubebuilder:object:root=true
type ReusableDelegationSetList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ReusableDelegationSet `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ReusableDelegationSet{}, &ReusableDelegationSetList{})
}
